<?php
/**
 * Pure/CookiesNotice
 * Author: Vladimir S. <guyasyou@gmail.com>
 * www.pure-web.ru
 * © 2017
 */

namespace Concrete\Package\PureCookiesNotice\Block\PureCookiesNotice;

use Concrete\Core\Block\BlockController;
use Concrete\Core\Editor\LinkAbstractor;
use Concrete\Core\File\Tracker\FileTrackableInterface;
use Concrete\Core\Statistics\UsageTracker\AggregateTracker;

defined('C5_EXECUTE') or die("Access Denied.");

class Controller extends BlockController implements FileTrackableInterface
{

    protected $btTable = "btPureCookiesNotice";
    protected $btDefaultSet = 'other';
    protected $btInterfaceWidth = "600";
    protected $btInterfaceHeight = "465";
    protected $btCacheBlockRecord = true;
    protected $btCacheBlockOutput = false;
    protected $btCacheBlockOutputOnPost = true;
    protected $btSupportsInlineEdit = false;
    protected $btSupportsInlineAdd = false;
    protected $btCacheBlockOutputLifetime = 0;

    public $title;
    public $content;
    public $agreeText = 'Ok';
    public $position = 'bottom';
    public $textColor = '#fff';
    public $backgroundColor = 'rgba(0, 40, 140, 0.8)';
    /**
     * @var \Concrete\Core\Statistics\UsageTracker\AggregateTracker
     */
    protected $tracker;


    public function getBlockTypeName()
    {
        return t('Cookies Notice');
    }

    public function getBlockTypeDescription()
    {
        return t('Cookies Notice allows you to inform users that your site uses cookies.');
    }

    public function __construct($obj=null, AggregateTracker $tracker=null)
    {
        parent::__construct($obj);
        $this->tracker = $tracker;
    }

    public function getContent()
    {
        return LinkAbstractor::translateFrom($this->content);
    }

    public function getSearchableContent()
    {
        return $this->title.' '.$this->content;
    }

    public function getContentEditMode()
    {
        return LinkAbstractor::translateFromEditMode($this->content);
    }

    public function br2nl($str)
    {
        $str = str_replace("\r\n", "\n", $str);
        $str = str_replace("<br />\n", "\n", $str);
        return $str;
    }

    public function getUsedFiles()
    {
        $files = [];
        $matches = [];
        if (preg_match_all('/\<concrete-picture[^>]*?fID\s*=\s*[\'"]([^\'"]*?)[\'"]/i', $this->content, $matches)) {
            list(,$ids) = $matches;
            foreach ($ids as $id) {
                $files[] = intval($id);
            }
        }

        return $files;
    }

    public function getUsedCollection()
    {
        return $this->getCollectionObject();
    }

    public function on_start()
    {
        parent::on_start(); // TODO: Change the autogenerated stub
        $this->requireAsset('javascript', 'jquery');
        $this->requireAsset('font-awesome');
    }

    public function add()
    {
        $this->set('position', 'bottom');
        $this->edit();
    }

    public function edit()
    {
        $this->requireAsset('css', 'pure_cookies_notice/edit');
        $this->set('positions', [
            'top' => t('Top'),
            'bottom' => t('Bottom'),
        ]);
    }

    public function view()
    {
        /** @var \Concrete\Core\Cookie\CookieJar $cookie */
        $cookie = \Core::make('cookie');
        if ($cookie->get('pureCookieNotify_'.$this->bID)) {
            $this->set('read', true);
        }
        $this->set('content', $this->getContent());
    }

    public function validate($data)
    {

        $e = \Core::make('error');

        if (empty($data['content'])) {
            $e->add(t('%s is required', 'Content'));
        }
        if (empty($data['position'])) {
            $e->add(t('%s is required', 'Position'));
        }

        return $e;
    }

    public function save($data)
    {
        /** @var \Concrete\Core\Utility\Service\Text $th */
        $th = \Core::make('helper/text');
        $data['title'] = $th->entities(trim($data['title']));

        $data['agreeText'] = $th->entities(trim($data['agreeText']));
        if (empty($data['agreeText'])) {
            $data['agreeText'] = 'Ok';
        }

        if (isset($data['content'])) {
            $data['content'] = LinkAbstractor::translateTo($data['content']);
        }

        parent::save($data);
        $this->tracker->track($this);
    }

    public function delete()
    {
        parent::delete();
        $this->tracker->forget($this);
    }

}
